{% set dataProductMajorVersion = values.identifier.split(".")[2] %}
{% set dataProductName = values.dataproduct.split(".")[1] | replace(" ", "") | replace("-", "") %}
{% set domainName = values.domain.split(":")[1] | replace(" ", "") | replace("-", "") %}
{% set componentName = values.name | replace(" ", "") | replace("-", "") | lower %}
{% set ComponentDependencies = values.dependsOn | list if values.dependsOn else [] %}

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.identifier }}
  description: ${{ values.description | dump }}
  annotations:
    gitlab.com/project-slug: ${{ values.owner + "/" + values.repo }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - outputport
spec:
  type: outputport
  lifecycle: experimental
  owner: ${{ values.developmentGroup }}
  system: ${{ values.dataproduct | dump }}
  domain: ${{ values.domain | dump }}
  mesh:
    name: ${{ values.name | dump }}
    fullyQualifiedName: ${{ values.domainName }} - ${{ values.dataproductName }} - version ${{ dataProductMajorVersion }} - ${{ values.name }}
    description: ${{ values.description | dump}}
    kind: outputport
    version: ${{ values.identifier.split(".")[2] + ".0.0" }}
    infrastructureTemplateId: ${{ values.infrastructureTemplateId }}
    useCaseTemplateId: ${{ values.useCaseTemplateId }}
    dependsOn:
        {% if values.dependsOn | length > 0 %}
        {% for i in values.dependsOn %}
        - ${{ i }}
        {% endfor %}
        {% else %}{% endif %}
        {% if values.storageArea not in ComponentDependencies %}
        - ${{ values.storageArea }}
        {% endif %}
    platform: AWS
    technology: Athena
    outputPortType: View
    creationDate: ${{ values.creationDate }}
    startDate: ${{ values.creationDate }}
    processDescription: ${{ values.processDescription | dump }}
    dataContract:
      schema: {% if values.schemaColumns | length > 0 %}
      {%- for column in values.schemaColumns %}
        {%- set primitiveType = column.arrayDataType if column.dataType == "ARRAY" else column.dataType %}
        - name: ${{ column.name }}
          dataType: ${{ column.dataType }}
      {%- if column.description %}
          description: ${{ column.description }}
      {%- endif %}
      {%- if column.constraint and column.constraint != "(no constraint)" %}
          constraint: ${{ column.constraint }}
      {%- endif %}
      {%- if primitiveType in ["VARCHAR", "CHAR"] and column.dataLength %}
          dataLength: ${{ column.dataLength }}
      {%- endif %}
      {%- if primitiveType == "DECIMAL" and column.precision %}
          precision: ${{ column.precision }}
      {%- endif %}
      {%- if primitiveType == "DECIMAL" and column.scale %}
          scale: ${{ column.scale }}
      {%- endif %}
      {%- if column.dataType == "ARRAY" and column.arrayDataType %}
          arrayDataType: ${{ column.arrayDataType }}
      {%- endif %}
          tags: {% if column.businessTerms | length > 0 %}{% for i in column.businessTerms %}
            - tagFQN: ${{ i }}
              source: Glossary
              labelType: Manual
              state: Confirmed
          {% endfor %}{% else %}[]{% endif %}
      {% endfor %}{% else %}[]{% endif %}
      termsAndConditions: ${{ values.termsAndConditions | dump }}
      endpoint: ${{ values.endpoint | dump }}
      SLA:
        intervalOfChange: ${{ values.intervalOfChange }}
        timeliness: ${{ values.timeliness }}
        upTime: ${{ values.upTime }}
    dataSharingAgreement:
      purpose: ${{ values.purpose | dump }}
      billing: ${{ values.billing | dump }}
      security: ${{ values.security | dump }}
      intendedUsage: ${{ values.intendedUsage | dump }}
      limitations: ${{ values.limitations | dump }}
      lifeCycle: ${{ values.lifeCycle | dump }}
      confidentiality: ${{ values.confidentiality | dump }}
    tags: []
    sampleData: {}
    semanticLinking: []
    specific:
      storageAreaId: ${{ values.storageArea | dump }}
      sourceTable:
        catalog: ${{ values.catalog | dump }}
        database: IGNORED
        name: ${{ values.sourceTableName | dump }}
      view:
        catalog: ${{ values.catalog | dump }}
        database: IGNORED
        name: ${{ componentName }}
